server:
  port: 8089
  ssl:
    key-store: classpath:swpuxytj.com.jks
    key-store-password: b7861bpt45             #压缩包解压里面会有
    key-store-type: JKS
    enabled: true
  my:
    httpsPort: 8089
    httpPort: 8080
spring:
  application:
    #应用的名称，可选
    name: XYTJ
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://124.223.48.82:3306/xytj?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: Zhangkuoyuan1230-9
  redis:
    host: 101.33.242.250
    port: 6379
    password: 20020329@redis
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
XYTJ:
#  path: D:\img\
  path: /usr/local/pic/


#spring.redis.host=124.223.15.33
#spring.redis.port=6379
